[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
cache = true
cache_path = "cache"
broadcast = "broadcast"
names = true
sizes = true

[profile.ci]
verbosity = 4

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}${ALCHEMY_API_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = "mainnet" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia" }
goerli = { key = "${ETHERSCAN_API_KEY}", chain = "goerli" }
mumbai = { key = "${POLYGON_API_KEY}", chain = "mumbai" }
optimism = { key = "${OPTIMISM_API_KEY}", chain = "optimism" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config